version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - npm install aws-cdk@2.96.1 -g
      - pip install constructs
      - pip install aws-cdk-lib
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - pwd && ls -l
      - cdk --version
  build:
    commands:
      - cd $(pwd)/cdk-jenkins
      - cdk deploy --require-approval never WebGoatStack
  post_build:
    commands:
      - echo Build completed on $(date)